name: Unit Test Workflow
on: pull_request

jobs:
  tests:
    name: Unit-Tests
    runs-on: macos-13
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run unit tests
        id: test_results
        run: |
          # Run the tests and generate coverage
          swift test --enable-code-coverage
          
          # Get the path to the codecov output
          COVERAGE_JSON=$(swift test --show-codecov-path)
          
          # Process the JSON data with jq to extract the relevant fields
          TABLE_CONTENT=$(jq -r '[.data[0].files[] 
            | select(.filename | test("Tests/") | not) 
            | "| \(.filename | split("/") | last) | \((.summary.lines.percent * 10 | round) / 10) |"] | join("\n")' "$COVERAGE_JSON")

          # Prepare the markdown table
          MARKDOWN_TABLE="| Filename | Coverage |\n|----------|----------|\n$TABLE_CONTENT"

          # Output the markdown table into a file so we can safely pass it to the comment
          echo "$MARKDOWN_TABLE" > table.md

      - name: Create PR comment with coverage table
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Unit Test Coverage Report

            $(cat table.md)
