name: Unit Test Workflow
on: pull_request

jobs:
  tests:
    name: Unit-Tests
    runs-on: macos-13
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Run unit tests
          run: |
            swift test --show-codecov-path
            swift test --enable-code-coverage
