name: Unit Test Workflow
on: pull_request

jobs:
  tests:
    name: SwiftLint
    runs-on: macos-13
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Run SwiftLint
          run: |
            set -o pipefail
            swiftlint lint --strict --quiet | sed -E 's/^(.*):([0-9]+):([0-9]+): (warning|error|[^:]+): (.*)/::\4 title=Lint error,file=\1,line=\2,col=\3::\5\n\1:\2:\3/'
